language: ruby
rvm: 2.1.5
services: postgresql
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.3
before_script:
  - psql -c 'create database guess_who_test;' -U postgres
script:
  - bundle exec rspec spec